-- Stergere tabele daca exista
DROP TABLE ANGAJATI;
DROP TABLE PROCENTE;

-- Creare tabela PROCENTE
CREATE TABLE PROCENTE (
  CAS_PROC NUMBER(5,2) DEFAULT 25,
  CASS_PROC NUMBER(5,2) DEFAULT 10,
  IMPOZIT_PROC NUMBER(5,2) DEFAULT 10,
  PAROLA VARCHAR2(100) DEFAULT 'student'
);

-- Creare tabela ANGAJATI
CREATE TABLE ANGAJATI (
  NR_CRT NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  NUME VARCHAR2(50) NOT NULL,
  PRENUME VARCHAR2(50) NOT NULL,
  FUNCTIE VARCHAR2(50),
  SALAR_BAZA INTEGER NOT NULL,
  SPOR_PROC NUMBER(5,2) DEFAULT 0,
  PREMII_BRUTE INTEGER DEFAULT 0,
  TOTAL_BRUT INTEGER,
  BRUT_IMPOZABIL INTEGER,
  CAS INTEGER,
  CASS INTEGER,
  IMPOZIT INTEGER,
  RETINERI INTEGER DEFAULT 0,
  VIRAT_CARD INTEGER,
  POZA BLOB
);

-- Date initiale PROCENTE
INSERT INTO PROCENTE VALUES (25, 10, 10, 'student');

-- Date de test ANGAJATI
INSERT INTO ANGAJATI (NUME, PRENUME, FUNCTIE, SALAR_BAZA, SPOR_PROC, PREMII_BRUTE, RETINERI)
VALUES ('Popescu', 'Ion', 'Inginer', 4000, 10, 0, 0);

COMMIT;